local Config = {
    Settings = {
        Theme = "Lime Dark",
        Acrylic = true,
        Transparency = true,
        MenuKeybind = "RightControl"
    },
    Combat = {
        Aimbot = false,
        AimKey = "MouseButton2",
        Smoothness = 5,
        FOV = 100,
        ShowFOV = true
    },
    Visuals = {
        ESP = false,
        BoxESP = true,
        NameESP = true,
        HealthBar = true,
        MaxDistance = 1000
    },
    Colors = {
        Accent = Color3.fromRGB(163, 230, 53),
        Background = Color3.fromRGB(11, 14, 12),
        Text = Color3.fromRGB(233, 240, 234)
    }
}

return Config
